---
# Copyright 2021 The MathWorks, Inc.
name: "current-release"

on:
  workflow_dispatch:
  schedule:
    # This schedule forces a rebuild of current on the 1st of the month
    - cron:  '0 0 1 * *'

jobs:
  current-release:
    name: "Current Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v2.3.4"

      - name: "Build & test"
        shell: bash
        run: |
          DOCKER_BUILDKIT=1 docker build --build-arg DIST_BASE=debian --build-arg DIST_TAG=stretch  --output type=local,dest=. .
          DOCKER_BUILDKIT=1 docker build --build-arg DIST_BASE=debian --build-arg DIST_TAG=buster   --output type=local,dest=. .
          DOCKER_BUILDKIT=1 docker build --build-arg DIST_BASE=debian --build-arg DIST_TAG=bullseye --output type=local,dest=. .
          DOCKER_BUILDKIT=1 docker build --build-arg DIST_BASE=ubuntu --build-arg DIST_TAG=bionic   --output type=local,dest=. .
          DOCKER_BUILDKIT=1 docker build --build-arg DIST_BASE=ubuntu --build-arg DIST_TAG=focal    --output type=local,dest=. .
          DOCKER_BUILDKIT=1 docker build --build-arg DIST_BASE=ubuntu --build-arg DIST_TAG=hirsute  --output type=local,dest=. .

      - name: "Get License to release under"
        shell: bash
        run: |
          wget -q -O COPYING  'https://sourceware.org/git/?p=glibc.git;a=blob_plain;f=COPYING;hb=HEAD'
          wget -q -O LICENSES 'https://sourceware.org/git/?p=glibc.git;a=blob_plain;f=LICENSES;hb=HEAD'

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "current"
          prerelease: false
          title: "Current Builds for Common Platforms"
          files: |
            build/*.deb
            COPYING
            LICENSES      