# Copyright 2021 The MathWorks, Inc.
---
name: "release-all"

# Build and release all artifacts is either triggered manually or on the first day of the month to 
# ensure all artifacts are up-to-date with security and other patches to these distributions
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 1 * *'  

jobs:
  build-debian-stretch:
    uses: mathworks/build-glibc-bz-19329-patch/.github/workflows/build-glibc-and-release.yaml@main
    with: 
      dist-base: debian
      dist-tag: stretch
    concurrency: artifact-release

  build-debian-buster:
    uses: mathworks/build-glibc-bz-19329-patch/.github/workflows/build-glibc-and-release.yaml@main
    with: 
      dist-base: debian
      dist-tag: buster
    concurrency: artifact-release

  build-debian-bullseye:
    uses: mathworks/build-glibc-bz-19329-patch/.github/workflows/build-glibc-and-release.yaml@main
    with: 
      dist-base: debian
      dist-tag: bullseye
    concurrency: artifact-release

  build-ubuntu-bionic:
    uses: mathworks/build-glibc-bz-19329-patch/.github/workflows/build-glibc-and-release.yaml@main
    with: 
      dist-base: ubuntu
      dist-tag: bionic
    concurrency: artifact-release

  build-ubuntu-focal:
    uses: mathworks/build-glibc-bz-19329-patch/.github/workflows/build-glibc-and-release.yaml@main
    with: 
      dist-base: ubuntu
      dist-tag: focal
    concurrency: artifact-release

  build-ubuntu-hirsute:
    uses: mathworks/build-glibc-bz-19329-patch/.github/workflows/build-glibc-and-release.yaml@main
    with: 
      dist-base: ubuntu
      dist-tag: hirsute
    concurrency: artifact-release
