---
name: "release-ubuntu-bionic"

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 2 1 * *'

jobs:
  build:
    uses: mathworks/build-glibc-bz-19329-patch/.github/workflows/build-glibc-and-release.yaml@main
    with: 
      dist-base: ubuntu
      dist-tag: bionic