---
name: "release-debian-bullseye"

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 5 1 * *'

jobs:
  build:
    uses: mathworks/build-glibc-bz-19329-patch/.github/workflows/build-glibc-and-release.yaml@main
    with: 
      dist-base: debian
      dist-tag: bullseye