---
name: "release-specific"

# To release a spcific set of artifacts using this workflow you can use the github CLI to trigger
# a workflow dispatch. An example of this for ubuntu:focal would be:
#
#   gh workflow run release-specific -f dist-base=ubuntu -f dist-tag=focal
on:
  workflow_dispatch:
    inputs:
      dist-base:
        required: true
        type: string
      dist-tag:
        required: true
        type: string

jobs:
  build:
    uses: mathworks/build-glibc-bz-19329-patch/.github/workflows/build-glibc-and-release.yaml@main
    with: 
      dist-base: ${{ github.event.inputs.dist-base }}
      dist-tag:  ${{ github.event.inputs.dist-tag }}