# Copyright 2021-2022 The MathWorks, Inc.
---
name: "release-all-debian"

# Build and release all artifacts is either triggered manually or on the first day of the month to 
# ensure all artifacts are up-to-date with security and other patches to these distributions
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 1 * *'  

jobs:
  build-all-debian:
    strategy:
      matrix:
        tag: [stretch buster bullseye]
    uses: ./.github/workflows/build-glibc-and-release.yaml
    with: 
      dist-base: debian
      dist-tag: ${{ matrix.tag }}

  build-all-ubuntu:
    strategy:
      matrix:
        tag: [bionic focal hirsute]
    uses: ./.github/workflows/build-glibc-and-release.yaml
    with: 
      dist-base: ubuntu
      dist-tag: ${{ matrix.tag }}
